# 1.  Create a 3x3x3 array with random values

In [1]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.28343255 0.95478738 0.45331963]
  [0.19933026 0.47557024 0.35291996]
  [0.26106077 0.4306878  0.08955569]]

 [[0.95522157 0.99329947 0.43274418]
  [0.79467109 0.30629569 0.35202613]
  [0.34737615 0.01081223 0.26481725]]

 [[0.12968644 0.05198089 0.8812119 ]
  [0.41830903 0.65905498 0.72284803]
  [0.87149775 0.35335736 0.4568632 ]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
b=np.diag([1,2,3,4,5])
print(b)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [8]:
c = np.ones((3,3))
c = np.zeros((8,8))
c[1::2,::2] = 1
c[::2,1::2] = 1
print(c)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [23]:
x= np.random.random((5,5))
print("Raw Arry is :\n ",x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("\n\n After normalization:\n",x)

Raw Arry is :
  [[0.18774325 0.60884705 0.369165   0.05588605 0.11027054]
 [0.12208696 0.79715809 0.07936319 0.98838168 0.07455915]
 [0.47837024 0.86484313 0.20815617 0.76985852 0.12246008]
 [0.61174445 0.84018542 0.49064496 0.71214213 0.19623375]
 [0.03298237 0.30723094 0.09936013 0.6407995  0.40273339]]


 After normalization:
 [[0.16198555 0.60274765 0.35187657 0.02397289 0.08089619]
 [0.09326424 0.79984956 0.04854601 1.         0.0435177 ]
 [0.46617981 0.87069433 0.1833514  0.77127557 0.09365478]
 [0.6057803  0.84488553 0.47902755 0.71086482 0.17087241]
 [0.         0.28705125 0.06947646 0.63619172 0.38701202]]


# 5. How to find common values between two arrays?

In [24]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between Array1 and Array 2 :")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between Array1 and Array 2 :
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [28]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [31]:
d = np.random.randint(0,2,6)
print("1st array:",d)
e = np.random.randint(0,2,6)
print("2nd array:",e)
print("Above two arrays are equal or not!")
array_equal = np.allclose(d, e)
print(array_equal)

1st array: [0 1 1 1 1 0]
2nd array: [0 0 0 1 0 0]
Above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [35]:
f = np.random.random(10)
print("Raw Arry: \n ",f)
f[f.argmax()] = 0
print("\n Maximum value replaced by 0: \n ")
print(f)

Raw Arry: 
  [0.54295724 0.10476295 0.37559427 0.80715721 0.62190137 0.68743519
 0.6123031  0.81873605 0.26188612 0.96822575]

 Maximum value replaced by 0: 
 
[0.54295724 0.10476295 0.37559427 0.80715721 0.62190137 0.68743519
 0.6123031  0.81873605 0.26188612 0.        ]


# 9. How to print all the values of an array?

np.set_printoptions(threshold=np.nan)
Z = np.zeros((25,25))
print(Z)

# 10.Subtract the mean of each row of a matrix

In [38]:
g = np.random.rand(3,3)
print(g)
print("\nSubtract the mean of each row of the matrix:\n")
g = g - g.mean(axis=1, keepdims=True)
print(g)

[[0.29273196 0.05844569 0.01438171]
 [0.64007825 0.89664825 0.31001107]
 [0.45347951 0.05927736 0.76394031]]

Subtract the mean of each row of the matrix:

[[ 0.17087884 -0.06340743 -0.10747141]
 [ 0.02449906  0.28106906 -0.30556812]
 [ 0.02791378 -0.36628837  0.33837458]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [48]:
i = np.ones(10)
j = np.random.randint(0,len(i),20)
i += np.bincount(j, minlength=len(i))
print(i)

[4. 3. 2. 5. 2. 2. 4. 4. 3. 1.]


# 12.How to get the diagonal of a dot product?

In [51]:
A = np.random.randint(0,10,(3,3))
B = np.random.randint(0,10,(3,3))
np.diag(np.dot(A, B))

np.sum(A * B.T, axis=1)

np.einsum("ij,ji->i", A, B)

array([ 48, 138,  39])

# 13.How to find the most frequent value in an array?

In [52]:
k = np.random.randint(0,10,50)
print (k)
print('rank:', np.bincount(k).argmax())

[2 3 7 5 3 2 6 7 5 9 3 5 6 4 4 8 6 4 2 6 1 3 1 9 8 4 3 0 9 1 8 5 0 6 2 7 7
 6 4 9 6 7 6 7 1 5 8 4 9 2]
rank: 6


# 14.How to get the n largest values of an array

In [54]:
l = np.arange(10000)
np.random.shuffle(l)
n = 5
print (l[np.argsort(l)[-n:]])
print (l[np.argpartition(-l,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9998 9999 9996 9995]


# 15.How to create a record array from a regular array?

In [57]:
Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')